### ISSUE TITLE
Error thrown when running after install

### ISSUE THREAD

**Issue by johanbrook** [pushrocks/gulp-browser#13]
I got this after a fresh `npm install --save-dev gulp-browser`. Did you mean to have `beautylog` as a dev dependency?

```
module.js:338
    throw err;
    ^

Error: Cannot find module 'beautylog'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Johan/Projects/Code/lookback/lookback-mac-onboarding/node_modules/gulp-browser/index.js:28:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by pereirinha** [comment]
I'll keep an eye on it. Facing same issue

**Comment by sdaitzman** [comment]
:+1: with same issue

**Comment by philkunz** [comment]
Yes, this was a dumb bug... Must have slipped through somehow since I have beautylog as dependency in most other packages. Sorry for that.
gulp-browser@1.0.4 should work.

**Comment by sdaitzman** [comment]
Thank you @philkunz :smile:

**Comment by johanbrook** [comment]
Cool, thanks!

**Comment by pereirinha** [comment]
Hum. Didn't work for me. It still asks for beautylog dependency.
![gulp-browser](https://cloud.githubusercontent.com/assets/2189187/12705548/6f555110-c86b-11e5-976c-126dfce60828.jpg)

**Comment by pereirinha** [comment]
Just trashed `node_modules/` but the issue remains

**Comment by philkunz** [comment]
@pereirinha could you connect on here? https://ide.c9.io/lossless/testgbrowser 

Then we can quickly debug it together.

**Comment by philkunz** [comment]
just made a quick demo and it seems to work for me. The error at the beginning was explainable, since beautylog was required only as devDependency... it should work now.
